---
name: Release
on:
  push:
    tags: [v*]

jobs:
  main:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write
    steps:
      - uses: ncipollo/release-action@v1
